name: Linux RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Update System
        run: |
          sudo apt update

      - name: Install Desktop Environment
        run: |
          sudo apt install xfce4 xfce4-goodies xrdp -y
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

      - name: Fix XFCE Session
        run: |
          echo "startxfce4" > ~/.xsession
          chmod +x ~/.xsession
          echo "export XDG_CONFIG_DIRS=/etc/xdg" >> ~/.xsession

      - name: Create RDP User
        run: |
          PASSWORD=$(openssl rand -base64 12)
          sudo useradd -m rdp
          echo "rdp:$PASSWORD" | sudo chpasswd
          sudo adduser rdp sudo
          echo "RDP_USER=rdp" >> $GITHUB_ENV
          echo "RDP_PASS=$PASSWORD" >> $GITHUB_ENV

      - name: Show RDP Details
        run: |
          echo "==============================="
          echo "RDP Address: GitHub Runner IP"
          echo "Port: 3389"
          echo "User: $RDP_USER"
          echo "Password: $RDP_PASS"
          echo "==============================="

      - name: Keep Runner Alive
        run: |
          while true; do
            echo "RDP Server Running..."
            sleep 300
          done
